on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version"
        default: "0.0.0"
        required: true
        type: string
      release:
        type: boolean
        default: false
        description: "Release"
      beta:
        type: boolean
        default: true
        description: "Beta"
      draft:
        type: boolean
        default: true
        description: "Draft"

env:
  release-name: ${{ inputs.version }}${{ inputs.beta && ' Beta' || '' }}

jobs:
  build:
    runs-on: ${{ matrix.arch.runs-on }}

    strategy:
      fail-fast: false
      matrix:
        arch:
          - { name: win-x64, rid: win-x64, arch: x64, os: win, runs-on: windows-latest }
          - { name: win-x86, rid: win-x86, arch: x86, os: win, runs-on: windows-latest }
          - { name: win-arm64, rid: win-arm64, arch: arm64, os: win, runs-on: windows-latest }
          - { name: osx-x64, rid: osx-x64, arch: x64, os: osx, runs-on: macos-15-intel }
          - { name: osx-arm64, rid: osx-arm64, arch: arm64, os: osx, runs-on: macos-latest }
          - { name: linux-x64, rid: linux-x64, arch: x64, os: linux, runs-on: ubuntu-latest, linuxarch: x86_64}
          - { name: linux-arm64, rid: linux-arm64, arch: arm64, os: linux, runs-on: ubuntu-latest, linuxarch: aarch64}

    steps:
      # Setup
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            6.0.x
            8.0.x
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - uses: justalemon/VersionPatcher@v0.7.1
        with:
          version: ${{ inputs.version }}
          csproj-files: "OpenUtau/*.csproj"

      # Test
      - name: Test
        run: dotnet test OpenUtau.Test

      # Build
      - name: Restore
        run: dotnet restore OpenUtau -r ${{ matrix.arch.rid }}

      - name: Build (Windows and Linux)
        run: dotnet publish OpenUtau -c Release -r ${{ matrix.arch.rid }} --self-contained true -o bin/${{ matrix.arch.name }}/
        if: ${{ matrix.arch.os != 'osx' }}

      - name: Build (MacOS)
        run: dotnet msbuild OpenUtau -t:BundleApp -p:Configuration=Release -p:RuntimeIdentifier=${{ matrix.arch.rid }} -p:UseAppHost=true -p:SelfContained=true -p:OutputPath=../bin/${{ matrix.arch.name }}/
        if: ${{ matrix.arch.os == 'osx' }}
      
      - name: Write release channel info
        run: "@{Beta=$${{ inputs.beta }}} | ConvertTo-Json > bin/${{ matrix.arch.name }}/prefs-default.json"
        shell: pwsh

      # Create Zip
      - name: DirectML
        shell: cmd
        run: |
          curl -L https://www.nuget.org/api/v2/package/Microsoft.AI.DirectML/1.15.4 -o Microsoft.AI.DirectML.nupkg
          mkdir Microsoft.AI.DirectML
          tar -xf Microsoft.AI.DirectML.nupkg -C Microsoft.AI.DirectML
          copy /y Microsoft.AI.DirectML\bin\${{ matrix.arch.arch }}-${{ matrix.arch.os }}\DirectML.dll bin\${{ matrix.arch.name }}\
        if: ${{ matrix.arch.os == 'win' }}

      - name: Set executable permission
        run: chmod +x bin/${{ matrix.arch.name }}/OpenUtau
        if: ${{ matrix.arch.os == 'linux' }}

      # Upload Artifacts (non-release only, GitHub will zip the directory once)
      - uses: actions/upload-artifact@v4
        with:
          name: OpenUtau-${{ matrix.arch.name }}
          path: bin/${{ matrix.arch.name }}/
        if: ${{ !inputs.release }}

      # Appcast
      - name: Appcast Windows
        shell: cmd
        run: |
          python appcast.py -v=${{ inputs.version }} -o=windows -r=${{ matrix.arch.name }} -f=OpenUtau-${{ matrix.arch.name }}.zip
        if: ${{ inputs.release && matrix.arch.os == 'win' }}

      - name: Appcast macOS
        run: |
          python appcast.py -v=${{ inputs.version }} -o=macos -r=${{ matrix.arch.name }} -f=OpenUtau-${{ matrix.arch.name }}.zip
        if: ${{ inputs.release && matrix.arch.os == 'osx' }}

      - name: Appcast Linux
        run: |
          python appcast.py -v=${{ inputs.version }} -o=linux -r=${{ matrix.arch.name }} -f=OpenUtau-${{ matrix.arch.name }}.zip
        if: ${{ inputs.release && matrix.arch.os == 'linux' }}

      # Create Zip for Release
      - name: Create Zip (Windows)
        run: |
          cd bin/${{ matrix.arch.name }}
          7z a ../../OpenUtau-${{ matrix.arch.name }}.zip *
        if: ${{ inputs.release && matrix.arch.os == 'win' }}

      - name: Create Zip (Linux/macOS)
        run: |
          cd bin/${{ matrix.arch.name }}
          zip -r ../../OpenUtau-${{ matrix.arch.name }}.zip *
        if: ${{ inputs.release && matrix.arch.os != 'win' }}

      # Release
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ inputs.version }}
          name: ${{ env.release-name }}
          prerelease: ${{ inputs.beta }}
          draft: ${{ inputs.draft }}
          files: |
            appcast.${{ matrix.arch.name }}*.xml
            OpenUtau-${{ matrix.arch.name }}.zip
          body: |
            See [Getting Started](https://github.com/stakira/OpenUtau/wiki/Getting-Started) for how to use.

            If you encountered issues, see [FAQ](https://github.com/stakira/OpenUtau/wiki/FAQ)

            ## macOS says "This app is damaged"
            Open a terminal and run `xattr -rc /Applications/OpenUtau.app`. Try opening OpenUtau again.
        if: ${{ inputs.release }}
